// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CommitAndPush(arg1, arg2) {
  return window['go']['backend']['App']['CommitAndPush'](arg1, arg2);
}

export function CommitFiles(arg1, arg2) {
  return window['go']['backend']['App']['CommitFiles'](arg1, arg2);
}

export function CreateBranch(arg1) {
  return window['go']['backend']['App']['CreateBranch'](arg1);
}

export function GetBranches() {
  return window['go']['backend']['App']['GetBranches']();
}

export function GetCurrentBranch() {
  return window['go']['backend']['App']['GetCurrentBranch']();
}

export function GetCurrentRepo() {
  return window['go']['backend']['App']['GetCurrentRepo']();
}

export function GetGitDiff(arg1) {
  return window['go']['backend']['App']['GetGitDiff'](arg1);
}

export function GetGitStatus() {
  return window['go']['backend']['App']['GetGitStatus']();
}

export function GetRepoRoot() {
  return window['go']['backend']['App']['GetRepoRoot']();
}

export function InitRepo(arg1) {
  return window['go']['backend']['App']['InitRepo'](arg1);
}

export function PushChanges() {
  return window['go']['backend']['App']['PushChanges']();
}

export function SwitchBranch(arg1) {
  return window['go']['backend']['App']['SwitchBranch'](arg1);
}

export function ValidateRepo(arg1) {
  return window['go']['backend']['App']['ValidateRepo'](arg1);
}
