// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CommitAndPush(arg1:Array<string>,arg2:string):Promise<main.CommitResult>;

export function CommitFiles(arg1:Array<string>,arg2:string):Promise<main.CommitResult>;

export function CreateBranch(arg1:string):Promise<void>;

export function GetBranches():Promise<Array<main.Branch>>;

export function GetCurrentBranch():Promise<string>;

export function GetCurrentRepo():Promise<main.GitRepo>;

export function GetGitDiff(arg1:string):Promise<main.DiffResult>;

export function GetGitStatus():Promise<Array<main.FileStatus>>;

export function GetRepoRoot():Promise<string>;

export function InitRepo(arg1:string):Promise<void>;

export function PushChanges():Promise<void>;

export function SwitchBranch(arg1:string):Promise<void>;

export function ValidateRepo(arg1:string):Promise<boolean>;
